_wandb:
    value:
        cli_version: 0.24.2
        e:
            nbu6ykiv3lwiyhaf0n3ys7j5xbun6zmt:
                args:
                    - --server_address
                    - 127.0.0.1:8096
                    - --cid
                    - 12164-0
                    - --data_path
                    - /home/hkuiot/Desktop/Federated-Time-Series-Forecasting/dataset/5G-2y-firstcell-6stations-medium-mixed-l2-2months.csv
                    - --model_name
                    - lstm
                    - --prediction_steps
                    - "4"
                    - --local_num_layers
                    - "2"
                    - --global_num_layers
                    - "3"
                    - --epochs
                    - "5"
                    - --batch_size
                    - "64"
                    - --pattern_weighted_residual_heads
                    - --num_residual_heads
                    - "6"
                    - --residual_head_temperature
                    - "0.1"
                    - --residual_head_init_scale
                    - "0.01"
                    - --residual_head_scale
                    - "1.0"
                    - --spc_pattern_source
                    - y_hist
                    - --wandb
                    - --metrics_log_path
                    - /home/hkuiot/Desktop/Federated-Time-Series-Forecasting/benchmark_logs_l2_2months_noscale_baselines/pwrh_client_12164-0_L2_metrics.csv
                    - --model_save_path
                    - /home/hkuiot/Desktop/Federated-Time-Series-Forecasting/experiments/H4-sequence-pattern-alignment/saved_models_l2_2months/pwrh_{cid}_{model_name}_final.pt
                    - --prediction_save_path
                    - /home/hkuiot/Desktop/Federated-Time-Series-Forecasting/experiments/H4-sequence-pattern-alignment/saved_predictions_l2_2months/pwrh_{cid}_{model_name}_last_{num_lags}.csv
                codePath: client-hetero.py
                codePathLocal: client-hetero.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "60725108736"
                        used: "40538218496"
                email: shisiping1992@gmail.com
                executable: /home/hkuiot/miniconda3/envs/fed/bin/python3
                git:
                    commit: b8365eb21c03f3a4217779b54558edee2ec35d6c
                    remote: https://github.com/saber-shi/Federated-Time-Series-Forecasting.git
                host: hkuiot-orin-1
                memory:
                    total: "65853022208"
                os: Linux-5.10.120-tegra-aarch64-with-glibc2.26
                program: /home/hkuiot/Desktop/Federated-Time-Series-Forecasting/client-hetero.py
                python: CPython 3.8.20
                root: /home/hkuiot/Desktop/Federated-Time-Series-Forecasting
                startedAt: "2026-06-21T14:23:02.282365Z"
                writerId: nbu6ykiv3lwiyhaf0n3ys7j5xbun6zmt
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 61
            "4": 3.8.20
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-aarch64
cid:
    value: 12164-0
fedprox_mu:
    value: 0
global_num_layers:
    value: 3
hetero_fedavg:
    value: false
inclusive_fl:
    value: false
local_num_layers:
    value: 2
model_name:
    value: lstm
model_rate:
    value: 1
num_residual_heads:
    value: 6
pattern_weighted_residual_heads:
    value: true
spa_hfl:
    value: false
spc:
    value: false
