_wandb:
    value:
        cli_version: 0.24.2
        e:
            0pv6kzndl2ht8tumichfi3z9h6pkac0s:
                args:
                    - --server_address
                    - 127.0.0.1:8090
                    - --cid
                    - 12163-0
                    - --data_path
                    - /home/hkuiot/Desktop/Federated-Time-Series-Forecasting/dataset/5G-2y-firstcell-10stations-mixed-duration.csv
                    - --model_name
                    - lstm
                    - --prediction_steps
                    - "4"
                    - --local_num_layers
                    - "1"
                    - --global_num_layers
                    - "3"
                    - --epochs
                    - "2"
                    - --wandb
                    - --metrics_log_path
                    - /home/hkuiot/Desktop/Federated-Time-Series-Forecasting/benchmark_logs/plain_heterofl_client_12163-0_L1_metrics.csv
                    - --batch_size
                    - "64"
                codePath: client-hetero.py
                codePathLocal: client-hetero.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "60725108736"
                        used: "35301433344"
                email: shisiping1992@gmail.com
                executable: /home/hkuiot/miniconda3/envs/fed/bin/python3
                git:
                    commit: fe60b7eb4ad2038b128f718cb2d6398856add29b
                    remote: https://github.com/saber-shi/Federated-Time-Series-Forecasting.git
                host: hkuiot-orin-1
                memory:
                    total: "65853030400"
                os: Linux-5.10.120-tegra-aarch64-with-glibc2.26
                program: /home/hkuiot/Desktop/Federated-Time-Series-Forecasting/client-hetero.py
                python: CPython 3.8.20
                root: /home/hkuiot/Desktop/Federated-Time-Series-Forecasting
                startedAt: "2026-04-06T09:05:53.185361Z"
                writerId: 0pv6kzndl2ht8tumichfi3z9h6pkac0s
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 61
            "4": 3.8.20
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-aarch64
cid:
    value: 12163-0
global_num_layers:
    value: 3
local_num_layers:
    value: 1
model_name:
    value: lstm
spa_hfl:
    value: false
